version: "3.9"
services:
  db:
    platform: linux/amd64
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "secret-pw"
      MYSQL_ROOT_HOST: "%"
      MYSQL_INITDB_SKIP_TZINFO: "1" # Disable strict mode
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
      - "./initial.sql:/docker-entrypoint-initdb.d/initial.sql"
      - ./logs/mysql:/var/log/mysql

  # for WebUI
  adminer:
    image: adminer:4.8.1
    ports:
      - "8095:8080"
